### ISSUE TITLE
Use towncrier for pulling news fragments into CHANGES.rst

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.releaser#17]
Too often a PR has an entry for ``CHANGES.rst``, it gets merged, and the entry ends up under the wrong version header, or under bug fixes instead of new features, or in the middle of a different entry. See for example my fix here: https://github.com/plone/plone.app.upgrade/commit/c00689b34a61010233a47c8e5fcc09ecb863d762.
Also, when backporting a fix using `git cherry-pick`, I often get dozens of totally unrelated extra entries in `CHANGES.rst`.

Partially, this is possible because in most or all packages we have `.gitattributes` with as contents `CHANGES.rst merge=union`. This means git tries its best to merge things, without complaining about a conflict that needs to be fixed.
Removing this file does not completely solve it, because then you get the same problem manually: you need to fix the conflict yourself. The end result may be better, but it is also more work.

The `pip` project has been using [`towncrier`](https://pypi.org/project/towncrier/) for about a year now. The pip documentation explains [how to use it](https://pip.pypa.io/en/latest/development/#adding-a-news-entry). Basically, in a PR you would create a `news/1234.bugfix` file or a `news/42.feature` file.  You do not touch `CHANGES.rst`. At release time, the person doing the release calls `towncrier`, which handles updating `CHANGES.rst` and removing the news fragments.

I want to start using this for Plone packages as well.

It may not be useful for all packages. The most to be gained would be for packages that get lots of changes, or that have multiple active branches.

Let's explore this. I will have a PR ready in a minute.

What would need to be done?

- [x] Figure out what needs to be done for individual Plone packages. Decide on a standard configuration. See PR #19
- [x] Let `plone.releaser` call `towncrier` during the release phase, if the package-to-be-released has configuration for it. We have `zestreleaser.towncrier` for that now, see PR #19.
- [x] Change `mr.roboto` to check for either an entry in `CHANGES.rst` or an added news fragment. https://github.com/plone/mr.roboto/issues/48
- [x] Update the Plone documentation for developers, for example the [guidelines](https://docs.plone.org/develop/coredev/docs/guidelines.html) for creating a PR. PR #19 has an `ADD-A-NEWS-ITEM.rst` that can be used as a basis for that. In packages where we try out `towncrier`, we can point to that file for now.
- [x] Write about this on community.plone.org. See https://community.plone.org/t/using-towncrier-for-changes-rst-in-plone-packages/6486

**Comment by gforcada** [comment]
I'm +1 on this, maybe this bit of information is already enough to start discussing it on community.plone.org IMHO.

**Comment by mauritsvanrees** [comment]
Some links:
- PR for a `pyproject.toml` and some sample news fragments in `plone.releaser`: https://github.com/plone/plone.releaser/pull/18
- PR for support in `zest.releaser`: https://github.com/zestsoftware/zest.releaser/pull/279

**Comment by tisto** [comment]
@mauritsvanrees thanks for working on this! I went through the docs to amended a plone.restapi PR to use towncrier. From the docs, it is still unclear to me how the content of a file in the /news folder needs to look like. Can you point me to an example?

Here is what I did so far:

https://github.com/plone/plone.restapi/pull/618/files#diff-a22c27f2e51c37d9a29de56c90857851

**Comment by mauritsvanrees** [comment]
In many cases, you can give the snippet the same content as a commit message, except that you would add  `[username]` either on the same line or the next.  But a commit message may contain details that would be too much information in a changelog.

Simple ReStructuredText syntax is supported, but whitespace is unfortunately ignored, so you cannot use syntax that requires multiple lines, like a list.

When `towncrier` is run, the number of the snippet (so `123` in case of `news/123.bugfix`) will be automatically appended, using `#123`. Technically we could configure `pyproject.toml` to turn this into a functioning link, but sometimes it would need to be a link to an issue number in `CMFPlone` and sometimes an issue number in `plone.restapi` in your case. We cannot know which one, so we only use the number.
You *could* decide to manually include a ReStructuredText link to the correct issue in the snippet, but then you have duplicate information, which can be slightly ugly.

Anyway, two recent examples from `i18ndude`:

[66.feature](https://github.com/collective/i18ndude/blob/2bfc8b659c2d20063b08ed0e82f5629fff081490/news/66.feature):

```
Replaced buildout with pip for setting up test environment.
No longer test on Python 3.4 and 3.5. Do test on 3.7. Current test matrix: 2.7, 3.6, 3.7, pypy, pypy3.
[maurits]
```

[68.bugfix](https://github.com/collective/i18ndude/blob/eac54bd6b0a85f22929a689ea129b5372e2430d6/news/68.bugfix):

```
When no arguments are given, show the help.
This fixes error on some Python versions when calling 'bin/i18ndude' without arguments.
[maurits]
```

**Comment by tisto** [comment]
Thanks @mauritsvanrees for the clarification!
